import src.data
from src.dm import dm_details_v1, dm_list_v1, dm_create_v1, dm_remove_v1, dm_invite_v1, dm_leave_v1, dm_messages_v1
from src.error import AccessError, InputError

def test_dm_details():
    pass

def test_dm_list():
    pass

def test_dm_create():
    #! Make sure to clear before every test
    '''
    Possible tests to run:
        Ensuring dm_id and dm_name are correct when creating valid dm
        Ensuring that dm_ids are increasing in the right order
            Only adding channels
            One where we remove channel(s) in the middle but not the end
            One where we remove channel(s) at the end
        Name of the dm is only autogenerated when creating the dm - doesn't change when there are new/leaving members
        Correctly raises an InputError when [u_id] does not refer to a valid user
        Correctly raises an AccessError is thrown when the token passed in is not valid
    '''


def test_dm_remove():
    pass

def test_dm_invite():
    pass

def test_dm_leave():
    pass

def test_dm_messages():
    pass
